---
title: "Data Wrangling"
author: "Jill Cates"
date: '2018-01-14'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(lubridate)
library(forcats)
```


```{r}
data <- read_csv('data.csv')
```



```{r}
data <- data %>% 
  select('Unique Key', 'Created Date', 'Closed Date', 'Agency', 'Complaint Type', 'Location Type', 'Borough', 'Incident Address', 'Latitude', 'Longitude')

colnames(data) <- c('id', 'created_date', 'closed_date', 'agency', 'complaint_type', 'location_type', 'borough', 'incident_address', 'lat', 'long')

data$closed_date <- parse_date_time(data$closed_date, "%m/%d/%Y $I:%M:%S %p", tz = "EST5EDT")

data$created_date <- parse_date_time(data$created_date, "%m/%d/%Y %I:%M:%S %p", tz = "EST5EDT")


```



```{r}
# data <- data[data$created_date >= "2016-01-01" & data$created_date <= "2016-12-31", ]

data$borough <- data$borough %>%
  fct_recode("Brooklyn" = "BROOKLYN", "Queens" = "QUEENS", "Manhattan" = "MANHATTAN", "Staten Island" = "STATEN ISLAND", "Bronx" = "BRONX")

data <- data %>% 
  filter(borough != 'Unspecified')
data$borough <- as.factor(data$borough)

data$month_created <- month(data$created_date)
data$year_created <- year(data$created_date)
data$day_created <- day(data$created_date)
data$hour_created <- hour(data$created_date)
data$weekday <- weekdays(data$created_date)

data$month_closed <- month(data$closed_date)
data$year_closed <- year(data$closed_date)
data$day_closed <- day(data$closed_date)

data$weekdays <- as.factor(data$weekday) %>%
  fct_recode("1" = "Monday", "2" = "Tuesday", "3" = "Wednesday", "4" = "Thursday", "5" = "Friday", "6" = "Saturday", "7" = "Sunday")
head(data)
#write_csv(data, 'data_wrangled.csv')

data %>% 
  group_by(weekday) %>% 
  summarise(
    count = n()
  )
```


```{r}
by_month <- data %>% 
  group_by(month_created, borough) %>% 
  summarise(
    count = n()
  )

by_month %>% 
  spread(borough, count)

average <- by_month %>% 
  ungroup() %>% 
  group_by(month_created) %>% 
  summarise(
    count = sum(count)/5
  )
average$borough <- rep("Average", 12)


df <- data.frame(average$month_created, average$borough, average$count)
colnames(df) <- c("month_created", "borough", "count")


df2 <- data.frame(by_month$month_created, by_month$borough, by_month$count)
colnames(df2) <- c("month_created", "borough", "count")

newdf <- rbind(df, df2)

newdf$month <- as.factor(newdf$month_created) %>%
  fct_recode("Jan" = "1", "Feb" = "2", "March" = "3", "April" = "4", "May" = "5", "June" = "6", "July" = "7", "Aug" = "8", "Sept" = "9", "Oct" = "10", "Nov" = "11", "Dec" = "12")

newdf$borough <- as.factor(newdf$borough) %>% 
  fct_recode("StatenIsland" = "Staten Island")

#write_csv(newdf, "data_by_month.csv")
```




```{r}
newdf2 <- newdf %>% 
  spread(borough, count) 
#write_csv(newdf2, 'data_by_month2.csv')
```